name: Dagster Branch Deployments
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
env:
  DAGSTER_CLOUD_URL: ${{ secrets.DAGSTER_CLOUD_URL }}
  REGISTRY_URI: ${{ secrets.REGISTRY_URI }}

jobs:
  dagster_cloud_build_push:
    runs-on: ubuntu-latest
    name: Dagster Branch Deployments
    strategy:
      fail-fast: false
      matrix:
        # Here, define the code locations that should be built and deployed
        location:
          - name: example_location
            build_folder: example_location
            registry_env: REGISTRY_URI
            location_file: cloud_workspace.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Notify build start
        uses: dagster-io/cloud-branch-deployments-action/notify@main
        with:
          action: "pending"
          pr: "${{ github.event.number }}"
          location: ${{ toJson(matrix.location) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.location.build_folder }}
          push: true
          tags: "${{ secrets.REGISTRY_URI }}:${{ github.sha }}"
          labels: |
            branch=${{ github.head_ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Dagster Cloud
        uses: dagster-io/cloud-branch-deployments-action/deploy@main
        id: deploy
        with:
          pr: "${{ github.event.number }}"
          pr_status: "${{ github.event.pull_request.merged && 'merged' || github.event.pull_request.state }}"
          location: ${{ toJson(matrix.location) }}
          image_tag: ${{ github.sha }}
        env:
          DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}

      - name: Notify build success
        uses: dagster-io/cloud-branch-deployments-action/notify@main
        with:
          action: "complete"
          pr: "${{ github.event.number }}"
          location: ${{ toJson(matrix.location) }}
          deployment: ${{ steps.deploy.outputs.deployment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify build failure
        if: ${{ failure() }}
        uses: dagster-io/cloud-branch-deployments-action/notify@main
        with:
          action: "failed"
          pr: "${{ github.event.number }}"
          location: ${{ toJson(matrix.location) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
